### ISSUE TITLE
Replace rawgit resources

### ISSUE THREAD

**Issue by SimonbJohnson** [SimonbJohnson/quickX3#65]
Rawgit could close down at anytime.  Migrate files referenced there:
https://rawgit.com/

**Comment by fititnt** [comment]
Maybe from this:

https://github.com/SimonbJohnson/quickX3/blob/5e21b5a59232dae25bd25eb9835d52447f384de8/hxldash/templates/base/base.html#L33-L35

To this:

```html
<script src="https://unpkg.com/chartist-plugin-legend@0.6.2/chartist-plugin-legend.js"></script> 
 <script src="{% static 'libs/chartist-plugin-tooltip.js' %}"></script> 
 <link rel="stylesheet" type="text/css" href="https://unpkg.com/chartist-plugin-tooltips@0.0.17/dist/chartist-plugin-tooltip.css" /> 
```

One problem I found is that https://rawgit.com/CodeYellowBV/chartist-plugin-legend/master/chartist-plugin-legend.js is not the same as the https://unpkg.com/chartist-plugin-legend@0.6.2/chartist-plugin-legend.js.

Here the quick diff of these files https://www.diffchecker.com/NLSdkzuu.

The reason for this difference (I did not tested if it could break the interface, so at this point will not just send a PR) seems to be the did not released a version and then pushed to NPM, so the unpkg.com will point to the old release without these new commits https://github.com/CodeYellowBV/chartist-plugin-legend/compare/v0.6.2...master.

**Comment by SimonbJohnson** [comment]
Fixed https://github.com/SimonbJohnson/quickX3/pull/77
