### ISSUE TITLE
[encoding] Move <meta charset="UTF-8"> to be the first subelement of <head> to help with some specific encoding errors

### ISSUE THREAD

**Issue by fititnt** [SimonbJohnson/quickX3#75]
Refs:
- #74 (with 74, if at some point later the title of the page become user configurable, and the user enter an non-ACII title of the map, this will cause unicode bugs)

---

On some cases (this may affect at least crawlers that may default to a non-UTF-8 encoding until find the charset tag, but at this point they may get wrong the <title> encoding) by not having the ` <meta charset="UTF-8">` as one of the first elements of the <head> this may lead to some bugs. I'm not fully 100% sure if this affects screen readers.

So the end code that today is this

```html
<!DOCTYPE HTML>
<html>
    <head>
        <title>HXL Dash</title>
<meta charset="UTF-8">
(...)
```

Could be this

```html
<!DOCTYPE HTML>
<html>
    <head>
        <meta charset="UTF-8">
        <title>HXL Dash</title>
(...)
```

**Comment by SimonbJohnson** [comment]
Fixed https://github.com/SimonbJohnson/quickX3/pull/77
