### ISSUE TITLE
ISO2 not finding geom

### ISSUE THREAD

**Issue by SimonbJohnson** [SimonbJohnson/quickX3#79]
Matching to geom in HXLbitesMap.js not happening with ISO2 codes.

No ISO2 here, add to list below ISO3.
https://github.com/SimonbJohnson/quickX3/blob/master/hxldash/static/libs/hxlbites/hxlBitesMap.js#L58-L61

Need to add new Geom with ISO3 and ISO2 codes. Current Geom has lots of redundant attributes:
https://hxldash.com/static/geoms/world.json

ISO and ISO3 codes in this file:
https://docs.google.com/spreadsheets/d/1Kye7WElskj6M9t23aCAWusINJLQuyTum0MeNKxS7rrI/edit#gid=0
Not sure how good the coverage is.

The matching happens here, but seems already set up to accept multiple code types:
https://github.com/SimonbJohnson/quickX3/blob/master/hxldash/static/libs/hxlbites/hxlBites.js#L729-L744

Example dataset with ISO2:
https://hxldash.com/create/https%3A%2F%2Fproxy.hxlstandard.org%2Fdata.csv%3Ftagger-match-all%3Don%26tagger-01-header%3Dbudget_amount%26tagger-01-tag%3D%2523value%252Bbudget%26tagger-03-header%3Dend_date%26tagger-03-tag%3D%2523date%252Bend%26tagger-07-header%3Dmodified_at%26tagger-07-tag%3D%2523date%252Bupdate%26tagger-08-header%3Dname%26tagger-08-tag%3D%2523activity%252Bname%26tagger-10-header%3Doperation_type_display%26tagger-10-tag%3D%2523operations%252Btype%26tagger-12-header%3Dprimary_sector_display%26tagger-12-tag%3D%2523sector%26tagger-14-header%3Dprogramme_type_display%26tagger-14-tag%3D%2523operations%252Btype2%26tagger-17-header%3Dproject_country_detail.iso%26tagger-17-tag%3D%2523country%252Bcode%26tagger-18-header%3Dproject_country_detail.name%26tagger-18-tag%3D%2523country%252Bname%26tagger-20-header%3Dproject_country_detail.society_name%26tagger-20-tag%3D%2523org%252Bimplementor%26tagger-29-header%3Dreached_female%26tagger-29-tag%3D%2523reached%252Bf%26tagger-30-header%3Dreached_male%26tagger-30-tag%3D%2523reached%252Bm%26tagger-31-header%3Dreached_other%26tagger-31-tag%3D%2523reached%252Bo%26tagger-32-header%3Dreached_total%26tagger-32-tag%3D%2523reached%252Btotal%26tagger-40-header%3Dreporting_ns_detail.society_name%26tagger-40-tag%3D%2523org%252Bpartner%26tagger-49-header%3Dstart_date%26tagger-49-tag%3D%2523date%252Bstart%26tagger-51-header%3Dstatus_display%26tagger-51-tag%3D%2523status%26tagger-52-header%3Dtarget_female%26tagger-52-tag%3D%2523target%252Bf%26tagger-53-header%3Dtarget_male%26tagger-53-tag%3D%2523target%252Bm%26tagger-54-header%3Dtarget_other%26tagger-54-tag%3D%2523target%252Bo%26tagger-55-header%3Dtarget_total%26tagger-55-tag%3D%2523target_total%26url%3Dhttps%253A%252F%252Fgoadmin.ifrc.org%252Fapi%252Fv2%252Fproject%252F%253Fformat%253Dcsv%26header-row%3D1%26dest%3Ddata_view

**Comment by Rydela** [comment]
On it!

**Comment by SimonbJohnson** [comment]
Fixed https://github.com/SimonbJohnson/quickX3/pull/80
